/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 scene.gltf 
Author: Asjohn720 (https://sketchfab.com/asjohn720)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/iphone-14-pro-max-3d-model-10929b58d74b4073a9de45183ac0f526
Title: iPhone 14 Pro Max 3d Model
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

 function Model(props) {
  const { nodes, materials } = useGLTF('./scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 1.393]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_4.geometry} material={materials['Material.006']} position={[0.076, 3.441, 0.4]} scale={[0.025, 0.443, 0.44]} />
          <mesh geometry={nodes.Object_6.geometry} material={materials['Material.003']} position={[-0.046, 3.793, -0.045]} scale={0.02} />
          <mesh geometry={nodes.Object_8.geometry} material={materials['Material.005']} position={[0, 2.905, 0.935]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.01, 0.009, 0.01]} />
          <mesh geometry={nodes.Object_10.geometry} material={materials['Material.005']} position={[0, 2.557, 0.935]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.01, 0.009, 0.01]} />
          <mesh geometry={nodes.Object_12.geometry} material={materials['Material.005']} position={[0, 2.634, -1.023]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.01, 0.009, 0.015]} />
          <mesh geometry={nodes.Object_14.geometry} material={materials['Material.001']} position={[0.007, 1.26, 0]} scale={[0.5, 1, 1]} />
          <mesh geometry={nodes.Object_16.geometry} material={materials['Material.005']} position={[0, 1.26, 0]} scale={[0.55, 1, 1]} />
          <mesh geometry={nodes.Object_18.geometry} material={materials['Material.007']} position={[0.027, 2.05, -0.036]} rotation={[0, 0, -Math.PI / 2]} scale={0.262} />
          <mesh geometry={nodes.Object_20.geometry} material={materials['iPhone_14_Pro_Wallpaper_Purple_YTECHB.com']} position={[-0.032, 1.965, -0.105]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[3.7, 1, 3.8]} />
          <mesh geometry={nodes.Object_22.geometry} material={materials['Material.003']} position={[-0.031, 1.965, -0.105]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[3.7, 1, 3.8]} />
          <mesh geometry={nodes.Object_24.geometry} material={materials.Material} position={[0.264, 3.461, 0.2]} rotation={[0, 0, -Math.PI / 2]} scale={0.169} />
          <mesh geometry={nodes.Object_26.geometry} material={materials.Material} position={[0.264, 3.68, 0.614]} rotation={[0, 0, -Math.PI / 2]} scale={0.169} />
          <mesh geometry={nodes.Object_28.geometry} material={materials.Material} position={[0.264, 3.237, 0.617]} rotation={[0, 0, -Math.PI / 2]} scale={0.169} />
          <mesh geometry={nodes.Object_30.geometry} material={materials['Material.002']} position={[0.264, 3.461, 0.2]} rotation={[0, 0, -Math.PI / 2]} scale={0.169} />
          <mesh geometry={nodes.Object_32.geometry} material={materials['Material.002']} position={[0.264, 3.68, 0.614]} rotation={[0, 0, -Math.PI / 2]} scale={0.169} />
          <mesh geometry={nodes.Object_34.geometry} material={materials['Material.002']} position={[0.264, 3.237, 0.617]} rotation={[0, 0, -Math.PI / 2]} scale={0.169} />
          <mesh geometry={nodes.Object_36.geometry} material={materials.Material} position={[0.168, 3.132, 0.198]} rotation={[0, 0, -Math.PI / 2]} scale={0.078} />
          <mesh geometry={nodes.Object_38.geometry} material={materials.Material} position={[0.111, 3.213, 0.055]} rotation={[0, 0, -Math.PI / 2]} scale={0.011} />
          <mesh geometry={nodes.Object_40.geometry} material={materials['Material.004']} position={[0.169, 3.786, 0.202]} rotation={[0, 0, -Math.PI / 2]} scale={0.078} />
        </group>
      </group>
    </group>
  )
}

export default Model;

useGLTF.preload('./scene.gltf')
